mv "./AD8认知障碍-自评量表" removed/
mv "./ADAS-Cog阿尔兹海默病评价-量表-" removed/
mv "./CDR临床痴呆-评定量表" removed/
mv "./Conners儿童行为问卷（父母用量表）/Conners儿童-行为问卷-（父母用量" removed/
mv "./Conners儿童行为问卷（父母用量表）/Conners儿童-行为问卷-（父母用量/icon.svg" removed/
mv "./Conners氏儿童-行为问卷-（教师用" removed/
mv "./GAD-7广泛性-焦虑量表" removed/
mv "./Hachinski缺血-指数量表（HIS" removed/
mv "./HAMA汉密尔顿-焦虑量表" removed/
mv "./MoCA蒙特利尔-认知评估量表" removed/
mv "./NPI神经精神科-问卷" removed/
mv "./SDS抑郁-自评量表" removed/
mv "./创伤后应激障碍-检查表" removed/
mv "./儿童孤独症-评定量表" removed/
mv "./儿童适应行为-评定量表" removed/
mv "./费城老年中心（PGC）-信心量表" removed/
mv "./孤独症行为-评定量表" removed/
mv "./家庭环境量表-中文版" removed/
mv "./克兰赛孤独症-行为量表" removed/
mv "./流调用抑郁-自评量表" removed/
mv "./脑能力测评" removed/
mv "./清晨型和夜晚型-自评量表" removed/
mv "./社交回避及苦恼-量表" removed/
mv "./生活满意度评定-量表（老年）" removed/
mv "./生活满意度指数A-（老年）" removed/
mv "./中文版GMFM-量表（88项）" removed/
